#ifndef COMMON_POLICY_TYPE_HPP_
#define COMMON_POLICY_TYPE_HPP_

#define NOTIFY_APPLY_RESULT     "8100"
#define NOTIFY_APPROVE_RESULT   "8101"
#define NOTIFY_CLIENT_LEVEL     "8102"

#endif /* COMMON_POLICY_TYPE_HPP_ */